<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250831102331 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE metier.aut_document DROP CONSTRAINT fk_demande');
        $this->addSql('ALTER TABLE metier.aut_validation_action DROP CONSTRAINT fk_validation_demande');
        $this->addSql('ALTER TABLE metier.aut_demande_document DROP CONSTRAINT fk_type_demande');
        $this->addSql('ALTER TABLE metier.aut_demande_document DROP CONSTRAINT fk_type_document');
        $this->addSql('DROP SEQUENCE perimetre_exploitation_forestiere_2015_gid_seq1 CASCADE');
        $this->addSql('DROP SEQUENCE type_document_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE document_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE metier.type_document_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE metier.nouvelle_demande_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE metier.type_demande_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE metier.type_demande_detail_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE metier.document_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE metier.etape_validation_id_seq CASCADE');
        $this->addSql('CREATE SEQUENCE metier.aut_etape_validation_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE metier.aut_nouvelle_demande_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE metier.aut_type_demande_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE metier.aut_type_demande_detail_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE metier.aut_type_document_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE metier.aut_etape_validation (id INT NOT NULL, demande_id INT NOT NULL, nom VARCHAR(255) NOT NULL, date_traitement TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, statut VARCHAR(50) NOT NULL, ordre INT NOT NULL, details TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_F9FED95F80E95E18 ON metier.aut_etape_validation (demande_id)');
        $this->addSql('CREATE TABLE metier.aut_nouvelle_demande (id INT NOT NULL, type_demande_id INT NOT NULL, raison_social VARCHAR(255) NOT NULL, operateur_id INT NOT NULL, code_suivie VARCHAR(20) NOT NULL, statut VARCHAR(255) NOT NULL, titre VARCHAR(255) DEFAULT NULL, description VARCHAR(255) DEFAULT NULL, desactivate BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_by VARCHAR(255) NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_by VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_483770589DEA883D ON metier.aut_nouvelle_demande (type_demande_id)');
        $this->addSql('COMMENT ON COLUMN metier.aut_nouvelle_demande.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN metier.aut_nouvelle_demande.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE metier.aut_type_demande (id INT NOT NULL, designation VARCHAR(255) NOT NULL, desactivate BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_by VARCHAR(255) NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_by VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN metier.aut_type_demande.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN metier.aut_type_demande.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE metier.aut_type_demande_detail (id INT NOT NULL, type_demande_id INT NOT NULL, type_document_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_FA4125C39DEA883D ON metier.aut_type_demande_detail (type_demande_id)');
        $this->addSql('CREATE INDEX IDX_FA4125C38826AFA6 ON metier.aut_type_demande_detail (type_document_id)');
        $this->addSql('CREATE TABLE metier.aut_type_document (id INT NOT NULL, designation VARCHAR(255) NOT NULL, desactivate BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_by VARCHAR(255) NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_by VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN metier.aut_type_document.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN metier.aut_type_document.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE metier.disponibilite_parc_billes (id INT NOT NULL, nom_vernaculaire VARCHAR(255) NOT NULL, nb_billes INT DEFAULT NULL, volume DOUBLE PRECISION DEFAULT NULL, code_usine INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE metier.disponibilite_parc_billons (id INT NOT NULL, nom_vernaculaire VARCHAR(255) NOT NULL, nb_billons INT DEFAULT NULL, volume DOUBLE PRECISION DEFAULT NULL, code_usine INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE metier.docs_stats (id INT NOT NULL, abv VARCHAR(100) NOT NULL, nb_delivres INT DEFAULT NULL, nb_saisi INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE essence_volume_top_10 (id INT NOT NULL, nom_vernaculaire VARCHAR(255) NOT NULL, cubage DOUBLE PRECISION NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE metier.import_data (id INT NOT NULL, type_fichier_id INT DEFAULT NULL, filename VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_by VARCHAR(255) NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_by VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_C3A5520412928ADB ON metier.import_data (type_fichier_id)');
        $this->addSql('CREATE TABLE metier.menu_permission (id INT NOT NULL, nom_menu VARCHAR(255) NOT NULL, icon_menu VARCHAR(100) NOT NULL, parent_menu INT NOT NULL, classname_menu VARCHAR(255) NOT NULL, code_groupe_id INT NOT NULL, id_permission INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE metier.performance_brh (id_performance INT NOT NULL, created_by VARCHAR(255) DEFAULT NULL, created_at DATE DEFAULT NULL, nb_ligne INT DEFAULT NULL, volume DOUBLE PRECISION NOT NULL, nb_brh INT DEFAULT NULL, PRIMARY KEY(id_performance))');
        $this->addSql('CREATE TABLE metier.performance_brh_jour (id_performance INT NOT NULL, created_at DATE DEFAULT NULL, nb_ligne INT DEFAULT NULL, volume DOUBLE PRECISION NOT NULL, nb_brh INT DEFAULT NULL, PRIMARY KEY(id_performance))');
        $this->addSql('CREATE TABLE metier.qt (id INT NOT NULL, id_exp INT DEFAULT NULL, numero_exp INT DEFAULT NULL, rs_exp VARCHAR(255) DEFAULT NULL, mrt_exp VARCHAR(255) DEFAULT NULL, numero_foret VARCHAR(255) DEFAULT NULL, id_usine INT DEFAULT NULL, date_chargementbrh DATE DEFAULT NULL, cubage DOUBLE PRECISION DEFAULT NULL, quota DOUBLE PRECISION DEFAULT NULL, rs_usine VARCHAR(255) DEFAULT NULL, tiers_quota DOUBLE PRECISION DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE metier.quota_transferable (id INT NOT NULL, id_exp INT DEFAULT NULL, numero_exp INT DEFAULT NULL, rs_exp VARCHAR(255) DEFAULT NULL, numero_foret VARCHAR(255) DEFAULT NULL, cubage DOUBLE PRECISION DEFAULT NULL, quota DOUBLE PRECISION DEFAULT NULL, tiers_quota DOUBLE PRECISION DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE statut_alerte (id INT NOT NULL, libelle VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE type_rapport (id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('ALTER TABLE metier.aut_etape_validation ADD CONSTRAINT FK_F9FED95F80E95E18 FOREIGN KEY (demande_id) REFERENCES metier.aut_nouvelle_demande (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE metier.aut_nouvelle_demande ADD CONSTRAINT FK_483770589DEA883D FOREIGN KEY (type_demande_id) REFERENCES metier.aut_type_demande (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE metier.aut_type_demande_detail ADD CONSTRAINT FK_FA4125C39DEA883D FOREIGN KEY (type_demande_id) REFERENCES metier.aut_type_demande (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE metier.aut_type_demande_detail ADD CONSTRAINT FK_FA4125C38826AFA6 FOREIGN KEY (type_document_id) REFERENCES metier.aut_type_document (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE metier.import_data ADD CONSTRAINT FK_C3A5520412928ADB FOREIGN KEY (type_fichier_id) REFERENCES metier.type_document_statistique (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE metier.agreement_commercant DROP CONSTRAINT fk_2b72a60213cf8b6');
        $this->addSql('ALTER TABLE metier.etape_validation DROP CONSTRAINT fk_etape_validation_demande');
        $this->addSql('ALTER TABLE metier.depot_commercant DROP CONSTRAINT fk_2b72a60213cf8b6');
        $this->addSql('DROP TABLE metier.agreement_commercant');
        $this->addSql('DROP TABLE metier.etape_validation');
        $this->addSql('DROP TABLE metier.nouvelle_demande');
        $this->addSql('DROP TABLE metier.depot_commercant');
        $this->addSql('DROP TABLE metier.type_demande');
        $this->addSql('DROP TABLE metier.type_document');
        $this->addSql('ALTER TABLE metier.attribution_pv ALTER date_decision TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE metier.attribution_pv ALTER date_decision SET NOT NULL');
        $this->addSql('ALTER TABLE metier.attribution_pv ALTER reprise SET NOT NULL');
        $this->addSql('DROP INDEX uq_type_demande_document');
        $this->addSql('DROP INDEX IDX_41FAADD99DEA883D');
        $this->addSql('DROP INDEX IDX_41FAADD98826AFA6');
        $this->addSql('ALTER TABLE metier.aut_demande_document ADD demande_id INT NOT NULL');
        $this->addSql('ALTER TABLE metier.aut_demande_document ADD document_id INT NOT NULL');
        $this->addSql('ALTER TABLE metier.aut_demande_document DROP type_demande_id');
        $this->addSql('ALTER TABLE metier.aut_demande_document DROP type_document_id');
        $this->addSql('ALTER TABLE metier.aut_demande_document ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE metier.aut_demande_document ADD CONSTRAINT FK_41FAADD980E95E18 FOREIGN KEY (demande_id) REFERENCES metier.aut_nouvelle_demande (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE metier.aut_demande_document ADD CONSTRAINT FK_41FAADD9C33F7837 FOREIGN KEY (document_id) REFERENCES metier.aut_document (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_41FAADD980E95E18 ON metier.aut_demande_document (demande_id)');
        $this->addSql('CREATE INDEX IDX_41FAADD9C33F7837 ON metier.aut_demande_document (document_id)');
        $this->addSql('DROP INDEX IDX_96B8EB7780E95E18');
        $this->addSql('ALTER TABLE metier.aut_document ADD desactivate BOOLEAN NOT NULL');
        $this->addSql('ALTER TABLE metier.aut_document ADD created_by VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE metier.aut_document ADD updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE metier.aut_document ADD updated_by VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE metier.aut_document DROP demande_id');
        $this->addSql('ALTER TABLE metier.aut_document ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE metier.aut_document ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN metier.aut_document.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN metier.aut_document.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE metier.aut_document ADD CONSTRAINT FK_96B8EB778826AFA6 FOREIGN KEY (type_document_id) REFERENCES metier.aut_type_document (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_96B8EB778826AFA6 ON metier.aut_document (type_document_id)');
        $this->addSql('ALTER TABLE metier.aut_validation_action ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE metier.aut_validation_action ALTER desactivate DROP DEFAULT');
        $this->addSql('ALTER TABLE metier.aut_validation_action ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE metier.aut_validation_action ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN metier.aut_validation_action.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN metier.aut_validation_action.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE metier.aut_validation_action ADD CONSTRAINT FK_F04609C280E95E18 FOREIGN KEY (demande_id) REFERENCES metier.aut_nouvelle_demande (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER INDEX metier.aut_validation_action_demande_id_idx RENAME TO IDX_F04609C280E95E18');
        $this->addSql('ALTER INDEX metier.aut_validation_action_validator_id_idx RENAME TO IDX_F04609C2B0644AEC');
        $this->addSql('DROP INDEX idx_e1052a9fcba8bd2');
        $this->addSql('ALTER TABLE metier.documentbcbgfh DROP code_reprise_id');
        $this->addSql('ALTER INDEX metier.idx_df9a63a2faaaec0a RENAME TO IDX_DF9A63A29DBC4D6C');
        $this->addSql('ALTER TABLE metier.documentetate2 ALTER code_generation_id SET NOT NULL');
        $this->addSql('ALTER TABLE metier.exploitant DROP agreeboo');
        $this->addSql('ALTER TABLE metier.exportateur DROP agree');
        $this->addSql('ALTER TABLE metier.fiche_prospection ALTER date_inventaire TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE metier.inventaire_forestier ALTER date_inventaire TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE metier.lignepagebcbp DROP CONSTRAINT fk_606d998b89d40298');
        $this->addSql('DROP INDEX idx_606d998b89d40298');
        $this->addSql('ALTER TABLE metier.lignepagebcbp DROP exercice_id');
        $this->addSql('ALTER TABLE metier.lignepagebtgu ALTER updated_by SET NOT NULL');
        $this->addSql('ALTER TABLE metier.lignepagelje DROP CONSTRAINT fk_97452d2920a1d299');
        $this->addSql('DROP INDEX idx_97452d2920a1d299');
        $this->addSql('ALTER TABLE metier.lignepagelje DROP code_pagebtgu_id');
        $this->addSql('ALTER TABLE metier.pagebcbp DROP immatcamion');
        $this->addSql('ALTER TABLE metier.pagebcbp DROP soumettre');
        $this->addSql('ALTER TABLE metier.pagebcbp DROP photo');
        $this->addSql('ALTER TABLE metier.pagebcbp DROP nb_billes');
        $this->addSql('ALTER TABLE metier.pagebcbp DROP volume');
        $this->addSql('ALTER TABLE metier.pagebcbp DROP entre_lje');
        $this->addSql('ALTER TABLE metier.pagebtgu DROP fini');
        $this->addSql('ALTER TABLE metier.pagebtgu DROP entre_lje');
        $this->addSql('ALTER TABLE metier.pagebtgu DROP soumettre');
        $this->addSql('ALTER TABLE metier.pageetate2 ALTER volumetotal SET NOT NULL');
        $this->addSql('ALTER TABLE metier.pageetate2 ALTER created_by SET NOT NULL');
        $this->addSql('ALTER TABLE metier.pagefp ALTER code_generation_id SET NOT NULL');
        $this->addSql('ALTER TABLE metier.pagepdtdrv ALTER numpage_pdtdrv SET NOT NULL');
        $this->addSql('DROP INDEX perimetre_exploitation_forestiere_2015_geom_idx');
        $this->addSql('ALTER TABLE pef ALTER gid DROP DEFAULT');
        $this->addSql('ALTER TABLE pef ALTER numero_pef SET NOT NULL');
        $this->addSql('ALTER TABLE pef ALTER zone_ SET NOT NULL');
        $this->addSql('ALTER TABLE pef ALTER zone_ TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE pef ALTER aire_pef TYPE NUMERIC(10, 0)');
        $this->addSql('ALTER TABLE pef ALTER aire_pef SET NOT NULL');
        $this->addSql('ALTER TABLE pef ALTER quotas TYPE NUMERIC(10, 0)');
        $this->addSql('ALTER TABLE pef ALTER quotas SET NOT NULL');
        $this->addSql('ALTER TABLE pef ALTER ta SET NOT NULL');
        $this->addSql('ALTER TABLE pef ALTER ts SET NOT NULL');
        $this->addSql('ALTER TABLE pef ALTER tas SET NOT NULL');
        $this->addSql('ALTER TABLE pef ALTER geom SET NOT NULL');
        $this->addSql('ALTER TABLE metier.reprise DROP motif');
        $this->addSql('ALTER TABLE metier.reprise ALTER numero_autorisation SET NOT NULL');
        $this->addSql('ALTER TABLE metier.reprise ALTER numero_autorisation TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE observateur.ticket ADD CONSTRAINT FK_6012DC1AF297FF5F FOREIGN KEY (code_cantonnement_id) REFERENCES metier.cantonnement (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE observateur.ticket ADD CONSTRAINT FK_6012DC1AEE3BAA66 FOREIGN KEY (code_oi_id) REFERENCES metier.oi (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_6012DC1AF297FF5F ON observateur.ticket (code_cantonnement_id)');
        $this->addSql('CREATE INDEX IDX_6012DC1AEE3BAA66 ON observateur.ticket (code_oi_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('CREATE SCHEMA pgagent');
        $this->addSql('ALTER TABLE metier.aut_demande_document DROP CONSTRAINT FK_41FAADD980E95E18');
        $this->addSql('ALTER TABLE metier.aut_validation_action DROP CONSTRAINT FK_F04609C280E95E18');
        $this->addSql('ALTER TABLE metier.aut_document DROP CONSTRAINT FK_96B8EB778826AFA6');
        $this->addSql('DROP SEQUENCE metier.aut_etape_validation_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE metier.aut_nouvelle_demande_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE metier.aut_type_demande_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE metier.aut_type_demande_detail_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE metier.aut_type_document_id_seq CASCADE');
        $this->addSql('CREATE SEQUENCE perimetre_exploitation_forestiere_2015_gid_seq1 INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE type_document_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE document_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE metier.type_document_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE metier.nouvelle_demande_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE metier.type_demande_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE metier.type_demande_detail_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE metier.document_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE metier.etape_validation_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE metier.agreement_commercant (id INT NOT NULL, code_commercant_id INT DEFAULT NULL, numero_dossier VARCHAR(25) NOT NULL, date_agreement DATE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_by VARCHAR(255) DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_by VARCHAR(255) DEFAULT NULL, statut BOOLEAN DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_93525DDCBEE9D0F5 ON metier.agreement_commercant (code_commercant_id)');
        $this->addSql('CREATE TABLE metier.etape_validation (id SERIAL NOT NULL, demande_id INT NOT NULL, nom VARCHAR(255) NOT NULL, date_traitement TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, statut VARCHAR(50) NOT NULL, ordre INT NOT NULL, details TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_367FC29880E95E18 ON metier.etape_validation (demande_id)');
        $this->addSql('CREATE TABLE metier.nouvelle_demande (id SERIAL NOT NULL, code_suivie VARCHAR(50) NOT NULL, type_demande_id INT NOT NULL, type_demande VARCHAR(100) DEFAULT NULL, operateur_id INT NOT NULL, raison_social VARCHAR(255) DEFAULT NULL, desactivate BOOLEAN DEFAULT false, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, created_by VARCHAR(100) DEFAULT NULL, update_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, update_by VARCHAR(100) DEFAULT NULL, statut VARCHAR(100) DEFAULT NULL, titre VARCHAR(100) DEFAULT NULL, description VARCHAR(100) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE metier.depot_commercant (id INT NOT NULL, numero_dossier_id INT DEFAULT NULL, numero_depot VARCHAR(25) NOT NULL, date_creation DATE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_by VARCHAR(255) DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_by VARCHAR(255) DEFAULT NULL, cc VARCHAR(50) DEFAULT NULL, ville VARCHAR(100) DEFAULT NULL, rc VARCHAR(50) DEFAULT NULL, quartier VARCHAR(50) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_60E165291E191F5 ON metier.depot_commercant (numero_dossier_id)');
        $this->addSql('CREATE TABLE metier.type_demande (id SERIAL NOT NULL, designation VARCHAR(255) NOT NULL, desactivate BOOLEAN DEFAULT false, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, created_by VARCHAR(100) NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, modified_by VARCHAR(100) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE metier.type_document (id SERIAL NOT NULL, designation VARCHAR(255) NOT NULL, desactivate BOOLEAN DEFAULT false, PRIMARY KEY(id))');
        $this->addSql('ALTER TABLE metier.agreement_commercant ADD CONSTRAINT fk_2b72a60213cf8b6 FOREIGN KEY (code_commercant_id) REFERENCES metier.commercant (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE metier.etape_validation ADD CONSTRAINT fk_etape_validation_demande FOREIGN KEY (demande_id) REFERENCES metier.nouvelle_demande (id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE metier.depot_commercant ADD CONSTRAINT fk_2b72a60213cf8b6 FOREIGN KEY (numero_dossier_id) REFERENCES metier.agreement_commercant (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE metier.aut_etape_validation DROP CONSTRAINT FK_F9FED95F80E95E18');
        $this->addSql('ALTER TABLE metier.aut_nouvelle_demande DROP CONSTRAINT FK_483770589DEA883D');
        $this->addSql('ALTER TABLE metier.aut_type_demande_detail DROP CONSTRAINT FK_FA4125C39DEA883D');
        $this->addSql('ALTER TABLE metier.aut_type_demande_detail DROP CONSTRAINT FK_FA4125C38826AFA6');
        $this->addSql('ALTER TABLE metier.import_data DROP CONSTRAINT FK_C3A5520412928ADB');
        $this->addSql('DROP TABLE metier.aut_etape_validation');
        $this->addSql('DROP TABLE metier.aut_nouvelle_demande');
        $this->addSql('DROP TABLE metier.aut_type_demande');
        $this->addSql('DROP TABLE metier.aut_type_demande_detail');
        $this->addSql('DROP TABLE metier.aut_type_document');
        $this->addSql('DROP TABLE metier.disponibilite_parc_billes');
        $this->addSql('DROP TABLE metier.disponibilite_parc_billons');
        $this->addSql('DROP TABLE metier.docs_stats');
        $this->addSql('DROP TABLE essence_volume_top_10');
        $this->addSql('DROP TABLE metier.import_data');
        $this->addSql('DROP TABLE metier.menu_permission');
        $this->addSql('DROP TABLE metier.performance_brh');
        $this->addSql('DROP TABLE metier.performance_brh_jour');
        $this->addSql('DROP TABLE metier.qt');
        $this->addSql('DROP TABLE metier.quota_transferable');
        $this->addSql('DROP TABLE statut_alerte');
        $this->addSql('DROP TABLE type_rapport');
        $this->addSql('ALTER TABLE observateur.ticket DROP CONSTRAINT FK_6012DC1AF297FF5F');
        $this->addSql('ALTER TABLE observateur.ticket DROP CONSTRAINT FK_6012DC1AEE3BAA66');
        $this->addSql('DROP INDEX IDX_6012DC1AF297FF5F');
        $this->addSql('DROP INDEX IDX_6012DC1AEE3BAA66');
        $this->addSql('ALTER TABLE metier.pageetate2 ALTER volumetotal DROP NOT NULL');
        $this->addSql('ALTER TABLE metier.pageetate2 ALTER created_by DROP NOT NULL');
        $this->addSql('ALTER TABLE metier.attribution_pv ALTER date_decision TYPE DATE');
        $this->addSql('ALTER TABLE metier.attribution_pv ALTER date_decision DROP NOT NULL');
        $this->addSql('ALTER TABLE metier.attribution_pv ALTER reprise DROP NOT NULL');
        $this->addSql('ALTER TABLE metier.documentbcbgfh ADD code_reprise_id INT DEFAULT NULL');
        $this->addSql('CREATE INDEX idx_e1052a9fcba8bd2 ON metier.documentbcbgfh (code_reprise_id)');
        $this->addSql('ALTER TABLE metier.inventaire_forestier ALTER date_inventaire TYPE DATE');
        $this->addSql('ALTER TABLE metier.documentetate2 ALTER code_generation_id DROP NOT NULL');
        $this->addSql('ALTER INDEX metier.idx_df9a63a29dbc4d6c RENAME TO idx_df9a63a2faaaec0a');
        $this->addSql('ALTER TABLE metier.pagefp ALTER code_generation_id DROP NOT NULL');
        $this->addSql('CREATE SEQUENCE pef_gid_seq');
        $this->addSql('SELECT setval(\'pef_gid_seq\', (SELECT MAX(gid) FROM pef))');
        $this->addSql('ALTER TABLE pef ALTER gid SET DEFAULT nextval(\'pef_gid_seq\')');
        $this->addSql('ALTER TABLE pef ALTER numero_pef DROP NOT NULL');
        $this->addSql('ALTER TABLE pef ALTER zone_ DROP NOT NULL');
        $this->addSql('ALTER TABLE pef ALTER zone_ TYPE VARCHAR(5)');
        $this->addSql('ALTER TABLE pef ALTER aire_pef TYPE DOUBLE PRECISION');
        $this->addSql('ALTER TABLE pef ALTER aire_pef DROP NOT NULL');
        $this->addSql('ALTER TABLE pef ALTER quotas TYPE DOUBLE PRECISION');
        $this->addSql('ALTER TABLE pef ALTER quotas DROP NOT NULL');
        $this->addSql('ALTER TABLE pef ALTER ta DROP NOT NULL');
        $this->addSql('ALTER TABLE pef ALTER ts DROP NOT NULL');
        $this->addSql('ALTER TABLE pef ALTER tas DROP NOT NULL');
        $this->addSql('ALTER TABLE pef ALTER geom DROP NOT NULL');
        $this->addSql('CREATE INDEX perimetre_exploitation_forestiere_2015_geom_idx ON pef (geom)');
        $this->addSql('ALTER TABLE metier.lignepagelje ADD code_pagebtgu_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE metier.lignepagelje ADD CONSTRAINT fk_97452d2920a1d299 FOREIGN KEY (code_pagebtgu_id) REFERENCES metier.pagebtgu (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_97452d2920a1d299 ON metier.lignepagelje (code_pagebtgu_id)');
        $this->addSql('ALTER TABLE metier.reprise ADD motif TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE metier.reprise ALTER numero_autorisation DROP NOT NULL');
        $this->addSql('ALTER TABLE metier.reprise ALTER numero_autorisation TYPE VARCHAR(100)');
        $this->addSql('DROP INDEX IDX_96B8EB778826AFA6');
        $this->addSql('ALTER TABLE metier.aut_document ADD demande_id INT NOT NULL');
        $this->addSql('ALTER TABLE metier.aut_document DROP desactivate');
        $this->addSql('ALTER TABLE metier.aut_document DROP created_by');
        $this->addSql('ALTER TABLE metier.aut_document DROP updated_at');
        $this->addSql('ALTER TABLE metier.aut_document DROP updated_by');
        $this->addSql('CREATE SEQUENCE metier.aut_document_id_seq');
        $this->addSql('SELECT setval(\'metier.aut_document_id_seq\', (SELECT MAX(id) FROM metier.aut_document))');
        $this->addSql('ALTER TABLE metier.aut_document ALTER id SET DEFAULT nextval(\'metier.aut_document_id_seq\')');
        $this->addSql('ALTER TABLE metier.aut_document ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN metier.aut_document.created_at IS NULL');
        $this->addSql('ALTER TABLE metier.aut_document ADD CONSTRAINT fk_demande FOREIGN KEY (demande_id) REFERENCES metier.nouvelle_demande (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_96B8EB7780E95E18 ON metier.aut_document (demande_id)');
        $this->addSql('ALTER TABLE metier.pagebcbp ADD immatcamion VARCHAR(20) DEFAULT NULL');
        $this->addSql('ALTER TABLE metier.pagebcbp ADD soumettre BOOLEAN DEFAULT NULL');
        $this->addSql('ALTER TABLE metier.pagebcbp ADD photo VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE metier.pagebcbp ADD nb_billes INT DEFAULT NULL');
        $this->addSql('ALTER TABLE metier.pagebcbp ADD volume DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE metier.pagebcbp ADD entre_lje BOOLEAN DEFAULT NULL');
        $this->addSql('ALTER TABLE metier.exploitant ADD agreeboo BOOLEAN DEFAULT NULL');
        $this->addSql('ALTER TABLE metier.lignepagebcbp ADD exercice_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE metier.lignepagebcbp ADD CONSTRAINT fk_606d998b89d40298 FOREIGN KEY (exercice_id) REFERENCES admin.exercice (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_606d998b89d40298 ON metier.lignepagebcbp (exercice_id)');
        $this->addSql('ALTER TABLE metier.fiche_prospection ALTER date_inventaire TYPE DATE');
        $this->addSql('CREATE SEQUENCE metier.aut_validation_action_id_seq');
        $this->addSql('SELECT setval(\'metier.aut_validation_action_id_seq\', (SELECT MAX(id) FROM metier.aut_validation_action))');
        $this->addSql('ALTER TABLE metier.aut_validation_action ALTER id SET DEFAULT nextval(\'metier.aut_validation_action_id_seq\')');
        $this->addSql('ALTER TABLE metier.aut_validation_action ALTER desactivate SET DEFAULT false');
        $this->addSql('ALTER TABLE metier.aut_validation_action ALTER created_at TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('ALTER TABLE metier.aut_validation_action ALTER updated_at TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('COMMENT ON COLUMN metier.aut_validation_action.created_at IS NULL');
        $this->addSql('COMMENT ON COLUMN metier.aut_validation_action.updated_at IS NULL');
        $this->addSql('ALTER TABLE metier.aut_validation_action ADD CONSTRAINT fk_validation_demande FOREIGN KEY (demande_id) REFERENCES metier.nouvelle_demande (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER INDEX metier.idx_f04609c2b0644aec RENAME TO aut_validation_action_validator_id_idx');
        $this->addSql('ALTER INDEX metier.idx_f04609c280e95e18 RENAME TO aut_validation_action_demande_id_idx');
        $this->addSql('ALTER TABLE metier.pagebtgu ADD fini BOOLEAN DEFAULT NULL');
        $this->addSql('ALTER TABLE metier.pagebtgu ADD entre_lje BOOLEAN DEFAULT NULL');
        $this->addSql('ALTER TABLE metier.pagebtgu ADD soumettre BOOLEAN DEFAULT NULL');
        $this->addSql('ALTER TABLE metier.aut_demande_document DROP CONSTRAINT FK_41FAADD9C33F7837');
        $this->addSql('DROP INDEX IDX_41FAADD980E95E18');
        $this->addSql('DROP INDEX IDX_41FAADD9C33F7837');
        $this->addSql('ALTER TABLE metier.aut_demande_document ADD type_demande_id INT NOT NULL');
        $this->addSql('ALTER TABLE metier.aut_demande_document ADD type_document_id INT NOT NULL');
        $this->addSql('ALTER TABLE metier.aut_demande_document DROP demande_id');
        $this->addSql('ALTER TABLE metier.aut_demande_document DROP document_id');
        $this->addSql('CREATE SEQUENCE metier.aut_demande_document_id_seq');
        $this->addSql('SELECT setval(\'metier.aut_demande_document_id_seq\', (SELECT MAX(id) FROM metier.aut_demande_document))');
        $this->addSql('ALTER TABLE metier.aut_demande_document ALTER id SET DEFAULT nextval(\'metier.aut_demande_document_id_seq\')');
        $this->addSql('ALTER TABLE metier.aut_demande_document ADD CONSTRAINT fk_type_demande FOREIGN KEY (type_demande_id) REFERENCES metier.type_demande (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE metier.aut_demande_document ADD CONSTRAINT fk_type_document FOREIGN KEY (type_document_id) REFERENCES metier.type_document (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE UNIQUE INDEX uq_type_demande_document ON metier.aut_demande_document (type_demande_id, type_document_id)');
        $this->addSql('CREATE INDEX IDX_41FAADD99DEA883D ON metier.aut_demande_document (type_demande_id)');
        $this->addSql('CREATE INDEX IDX_41FAADD98826AFA6 ON metier.aut_demande_document (type_document_id)');
        $this->addSql('ALTER TABLE metier.exportateur ADD agree BOOLEAN DEFAULT NULL');
        $this->addSql('ALTER TABLE metier.lignepagebtgu ALTER updated_by DROP NOT NULL');
        $this->addSql('ALTER TABLE metier.pagepdtdrv ALTER numpage_pdtdrv DROP NOT NULL');
    }
}
